# Generated by Django 3.1.5 on 2021-02-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingredient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.ingredient'),
        ),
    ]
