# Generated by Django 3.1.5 on 2021-02-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210202_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ingredient'),
        ),
    ]
