# Generated by Django 3.1.5 on 2021-02-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210202_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredient',
            field=models.ManyToManyField(null=True, to='order.Ingredient'),
        ),
    ]
